### ISSUE TITLE
May I get the source?

### ISSUE THREAD

**Issue by sirkkalap** [DaniMol/Restart-Finder-Dock#1]
Hi, Would you care to share the source code? Preferably under MIT or similar licence 👍

**Comment by DaniMol** [comment]
I’ve written it using AppleScript. 

Verstuurd vanaf mijn MacBook Pro

**Comment by DaniMol** [comment]
Copy and paste this in Scripteditor and save it as an application do shell script "killall -KILL Finder"do shell script "killall -KILL Dock"That’s allOp 12 dec. 2022 om 22:29 heeft Petri Sirkkala ***@***.***> het volgende geschreven:﻿
Closed #1 as not planned.
